### ISSUE TITLE
i want use cqrs at  npmjs , can i?

### ISSUE THREAD

**Issue by izengliang** [petrjanda/node-cqrs#9]
i want use cqrs at  npmjs , can i?

i develop a new cqrs domain project, i like `cqrs` name.

```
npm install cqrs
```

can i use it? make to me?

**Comment by petrjanda** [comment]
I've submitted the request to support at npm to help with the transfer. I CC'd you on your github account so you should be kept in the loop.

**Comment by izengliang** [comment]
thanks!
